kumuluzee:
  name: authentication-provider
  version: 3.0.0
  env:
    name: dev
  server:
    http:
      port: 9000
    https:
      port: 9443
  datasources:
    - jndi-name: jdbc/AuthProviderDS
      connection-url: jdbc:mysql://localhost:3306/authbv
      username: bv
      password: hwinkel
      max-pool-size: 20
  jwt-auth:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1csTKiAv4N3SwLNCA9r77Uzz/GZ5JIfOdUJziUonHPoprT/FTgtPFefRo9a+4KTYltG1gwv1VxR9IPueZFBsZkY/mwpnp1wUgQucDVf7jzQmAwLe9gxuUugDQ3UMdFvg+OgZhpjXYE2H/EQn0fmWWYr8VCaMH/bsSaZfuPy+7sozE5whM/8WdDGMp9GJ4NsUPhXBwhMzwC08Z/m5E+W4gX1YyRqCeposB8UtvM0CIjjbzFoQx9yfNx71C0prI7YCIrrgiJym6YmYHkBcFc9Gt6k2cWGmjZwxlO3I8vqCXYg/W7Fz3Sj9srcIuEnMXqb27bE2IhJvcbGgRRqeqXsA9QIDAQAB
    issuer: heike2718/authprovider
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-mapping
    scan:
      packages: de.egladil.web.authprovider
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 3600
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-check:
        jndi-name: jdbc/AuthProviderDS
  logs:
    config-file-location: /home/heike/git/authprovider/src/config/log4j2.xml
application-config:
  config-root: /home/heike/git/authprovider/src/config
  name-dynamic-config-file: dynamicConfigProperties.json
  target-origin: localhost:4200 localhost:4300
  block_on_missing_origin_referer: false
  heartbeat-id: heartbeat
  profil-client-id: T73pF0WTZLuFTv0nbXgqIiXAxyl935c4WCBNwq32uvfQ
  profil-client-secret: start123
password-config:
  pepper: z0eiPZVJxq/xhYD1RkXACJMKqtmzMQQ9blaR+ozXMk8=
  crypto-algorithm: SHA-256
  iterations: 4098
  random-algorithm: SHA1PRNG
  private-key-location: /home/heike/.keystore/private/authprov_private_key.pem
  public-key-location: /home/heike/.keystore/public/authprov_public_key.pem
  temp-pwd-length: 12
  temp-pwd-char-pool: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
  temp-pwd-url: http://localhost:4300/#/password/temp/change?tokenId=
email-config:
  host: smtp.strato.de
  port: 587
  user: noreply@egladil.de



